#stage 1
FROM node:17-alpine AS builder

WORKDIR /app



COPY package.json .
COPY package-lock.json .
RUN npm ci



COPY . .
RUN npm run build


#stage 2
FROM nginx:1.19.0
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build .
ENTRYPOINT ["nginx", "-g", "daemon off;"]